project:
  type: website
  resources:
    - .nojekyll
    - CNAME
    - "/res/*"
    - "/libs/*"
    - "/content/**/*.pdf"
  render:
    - "*.qmd"
    - "!TODO.md"
    - "!LICENSE.md"
    - "!test/"
    - "!src/"
    - "!libs/"

website:
  title: "ADTC"
  description: "Conference On Alzheimer's disease In Midt-Norge  \n International collaborative conference"
  favicon: "/res/img/JCA.png"
  bread-crumbs: true
  back-to-top-navigation: true
  site-url: https://www.adtc.no

  ### Navbar ###
  navbar:
    logo: "/res/img/JCA.png"
    pinned: true
    collapse: true
    collapse-below: md
    left:
      - href: index.qmd
        text: "{{< fa house height=20px >}} Home"
      - href: content/program/index.qmd
        text: "{{< fa calendar-days height=20px >}} Program"
      - href: content/talks/index.qmd
        text: "{{< iconify file-icons keynote height=20px >}} Talks"
      - href: content/people/index.qmd
        text: "{{< iconify bi people height=20px >}} People"
      - href: content/logistics/index.qmd
        text: "{{< fa car height=20px >}} Logistics"
  
  open-graph:
    title: "ADTC"
    description: "Join us in Trondheim for a conference on Alzheimer's disease state-of-the-art research, and explore translational breakthroughs with international experts."
    locale: en_US
    image: res/img/logo.png
    image-alt: "ADTC Conference Logo"
    site-name: "Alzheimer's Disease Translational Conference"
  twitter-card:
    title: "ADTC"
    description: "Join us in Trondheim for a conference on Alzheimer's disease state-of-the-art research, and explore translational breakthroughs with international experts."
    image: res/img/logo.png
    image-alt: "Alzheimer's Disease Translational Conference"
    card-style: summary
    creator: "@Agalic21"
  
  ### Search ###
  search:
    location: navbar
    type: overlay
    collapse-after: 2
    show-item-context: true
  
  ### Sidebar ###
  sidebar: false

  announcement: 
    content: "Conference [**registration**](https://docs.google.com/forms/d/e/1FAIpQLSeQIoCR2CXUVLiegQm6Rsh7Ph5LHKDiCepFcalr5sWBk5YlKA/viewform?usp=header) is now open" 
    position: below-navbar 
    icon: info-circle
    type: secondary
    dismissable: true

  ### Footer ###
  page-footer:
    border: true
    background: dark
    left:
      - text: "Norges Teknisk-Naturvitenskapelige Universitet"
        href: https://www.ntnu.no/
      - text: "Kavli Institute for Systems Neuroscience" 
        href: https://www.ntnu.edu/kavli/
    center: 
      - text: "© 2025, ADTC"
        href: LICENSE.md
        aria-label: "Website's license"
      - text: "Contact Us"
        href: mailto:contact@adtc.no
        aria-label: "Contact Us"
    right:
      - text: "St. Olavs hospital"
        href: https://www.stolav.no/
      - text: "Nasjonalforeningen for Folkehelsen"
        href: https://nasjonalforeningen.no/

lightbox: true

from: markdown+emoji
comments: false
toc: false

## Format options ##
brand: /_brand.yml

format:
  html:
    theme: [default, brand, libs/light.scss]
    css: libs/styles.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1200px
      margin-width: 250px
    df-print: paged
    fig-align: center
    fig-dpi: 500
    fig-format: svg
    anchor-sections: true
    footnotes-hover: true
    crossrefs-hover: true
    link-external-icon: true
    link-external-newwindow: true


## Execution / R options ##

engine: knitr

knitr:
  opts_chunk:
    warning: false
    message: false
    fig.align: center
    dpi: 500
    dev: svg
    dev.args:
      bg: transparent
    # R.options:
    #   scipen: 999
  opts_knit:
    verbose: false

execute:
  engine: knitr
  warning: false
  message: false
  echo: false
  cache: false
  freeze: auto

editor: source

# Templates: https://github.com/quarto-dev/quarto-cli/tree/f6b86d11b7d6a93b60f541982d3fe119ff484b15/src/resources/formats/html/templates