---
title: "Venue"
---

## The Venue

The conference will be held at **Kunskapssenteret (The Knowledge Centre)**, located within the St. Olavs Hospital campus, integrated with the Norwegian University of Science and Technology (NTNU).

**Address:** Olav Kyrres gate 17, Trondheim.

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7139.412669391062!2d10.37599988271547!3d63.42608308583068!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x466d319213c17705%3A0x457c7ea94a81628f!2sOlav%20Kyrres%20gate%2017%2C%207030%20Trondheim!5e0!3m2!1sen!2sno!4v1756327187171!5m2!1sen!2sno" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

Kunskapssenteret is a modern facility designed to foster collaboration and learning, situated centrally within the hospital and university area. It is well-connected by public transport and within reasonable distance of the city center and various accommodation options.

### Hosting Institutions

* **[Norwegian University of Science and Technology (NTNU)](https://www.ntnu.edu/){target="_blank"}:**
    NTNU is Norway's largest university, with a strong focus on science,
    technology, engineering, and medicine. It plays a central role in
    Trondheim's academic and research environment.
* **[Kavli Institute for Systems Neuroscience (KISN)](https://www.ntnu.edu/kavli/){target="_blank"}:**
    KISN is a major research centre in the field and is led by Nobel Laureates
    Edvard Moser and May-Britt Moser. The institute is comprised of 10 research
    groups with research interests including cognitive, molecular, computational
    and all other facets of neuroscience.
* **[K.G. Jebsen Centre for Alzheimer's Disease](https://www.ntnu.edu/kavli/k.g.-jebsen-centre-for-alzheimer-s-disease){target="_blank"}:**
    The K.G. Jebsen Centre for Alzheimer's Disease is led by Edvard Moser and
    Asgeir Kobro-Flatmoen. Comprised of interdisciplinary experts aiming to
    understand the onset and developpment of Alzheimer's, the center has
    translational reach thanks to tight collaboration with St Olavs Hospital.
* **[St. Olavs Hospital](https://stolav.no/){target="_blank"}:**
    The university hospital in Trondheim, closely integrated with NTNU's Faculty
    of Medicine and Health Sciences. The conference venue itself is part of the
    hospital complex.

### Funding institutions

**[Nasjonalforeningen for Folkehelsen](https://nasjonalforeningen.no/){target="_blank"}**: Nasjonalforeningen for Folkehelsen is a voluntary humanitarian organization working to combat cardiovascular diseases and dementia. As one of Norway’s leading public health organizations, they combine research funding, advocacy, and public health initiatives to improve the lives of those affected by these conditions.