---
title: "Program"
---

| Time | Activity |
|------|----------|
| **Program COAIM, dates TBA, 2025** | |
| **Day 1. Organization, function, and dysfunction of the memory system in connection with AD** | |
| | *Moderated by Heikki Tanila* |
| 12:30-13:50 | Registration and lunch |
| 13:55-14:00 | Welcoming address by organizers |
| 14:00-14:30 | Anatomical units of space, time and memory. Talk by Prof. Menno Witter, JCA/KISN |
| 14:30-14:40 | Questions and discussion |
| 14:40-15:10 | Functional units of space, time and memory. Talk by Prof. Edvard/May-Britt Moser, JCA/KISN |
| 15:10-15:20 | Questions and discussion |
| 15:20-15:50 | Imaging the anatomical and structural units of memory. Talk by Prof. Christian Döller, JCA/KISN and Max Planck Institute for Human Cognitive and Brain Sciences in Leipzig |
| 15:50-16:00 | Questions and discussion |
| 16:00-16:20 | Break with refreshments |
| 16:20-16:50 | Neuron-selective vulnerability in prodromal AD. Talk by Dr. Asgeir Kobro-Flatmoen, The National Union Dementia Centre, KISN, NTNU |
| 16:50-17:00 | Questions and discussion |
| 17:00-18:30 | Poster session 1 |
| 18:30-19:00 | The clinical presentation and diagnosis of AD. Talk by Dr. Gøril Rolfseng Grøntvedt, The National Union Dementia Centre, KISN, NTNU |
| 19:00-19:10 | Questions and discussion |
| 19:10-19:40 | Neurocognitive alterations of entorhinal functioning in preclinical AD. Talk by Prof. Nikolai Axmacher, Ruhr University, Bochum, Germany |
| 19:40-19:50 | Questions and discussion |
| 20:15-22:00 | Dinner |
| **Day 2, part 1. Central aspects of AD: proteinopathy** | |
| | *Moderated by Asgeir Kobro-Flatmoen* |
| 09:00-09:40 | Key note lecture – day 2. The filaments of tau and their impact on AD, by Prof. Michel Goedert, University of Cambridge |
| 09:40-09:50 | Questions and discussion |
| 09:50-10:20 | Sequence of protein changes in AD. Talk By Dietmar Thal, KU-Leuven |
| 10:20-10:30 | Questions and discussion |
| 10:30-11:00 | Tau and microglia and MTL. Talk by Prof Maria Grazia Spillantini, University of Cambridge |
| 11:00-11:10 | Questions and discussion Replacement needed |
| 11:10-11:30 | Break with refreshments |
| 11:30-12:00 | Early/initiating pathological interactions, Aβ, p-tau and ApoE. Talk by Prof. Gunnar Gouras, Experimental Dementia Research, Lund University |
| 12:00-12:10 | Questions and discussion |
| 12:10-12:40 | Endosomal dysfunction triggers intraneuronal beta-amyloid in late-onset AD. Talk by Prof. Claudia Almeida, NOVA Medical School, Lisbon, Portugal |
| 12:40-12:50 | Questions and discussion |
| 12:50-14:00 | Lunch |
| **Day 2, part 2. Central aspects of AD: Early cellular changes, behavior and cognition** | |
| | *Moderated by Tora Bonnevie* |
| 14:00-14:30 | Roles of inflammation in Alzheimer's disease and dementia. Talk by Prof. Paul Edison, Imperial College London, UK |
| 14:30-14:40 | Questions and discussion |
| 14:40-15:10 | Lifestyle and Dementia Risk: Does It Apply to Alzheimer's? Talk by Prof. Geir Selbæk, Norwegian National Advisory Unit on Ageing and Health, Norway |
| 15:10-15:20 | Questions and discussion |
| 15:20-16:30 | Poster session 2 |
| 16:30-17:00 | The viscious circle between neuronal hyperexcitability and AD. Talk by Prof. Heikki Tanila, Uni Eastern Finland |
| 17:00-17:10 | Questions and discussion |
| 17:10-17:40 | Modeling the onset of p-tau in rats. Talk by Prof. Cliff Kentros, KISN, NTNU |
| 17:40-17:50 | Questions and discussion |
| 17:50-18:10 | Break with refreshments |
| 18:10-18:40 | Microglial changes in early stages of AD. Talk by Prof. Kristine Freude, Department of Veterinary and Animal Sciences, UCPH, Denmark |
| 18:40-18:50 | Questions and discussion |
| 18:50-19:20 | Ethologically relevant phenotyping of cognitive impairments in AD model mice. Talk by Prof. Julija Krupic, University of Cambridge, UK |
| 19:20-19:30 | Questions and discussion |
| 19:30-20:00 | Fine-tuning the NAD+-mitophagy axis in healthy brain ageing. Talk by Prof. Evandro Fang |
| 20:00-20:10 | Questions and discussion |
| 20:30-22:30 | Dinner |
| **Day 3. Translational research on AD** | |
| | *Moderator: Prof. Gunnar Gouras* |
| 09:00-09:40 | Key note lecture - day 2. Translational research on the AD cascade, by Karen Duff, UK DRI Centre Director, University College London |
| 09:40-09:50 | Questions and discussion |
| 09:50-10:20 | Alzheimer's disease biomarkers reflecting neuronal and innate immune brain pathologies and pathomechanisms. Talk by Tormod Fladby |
| 10:20-10:40 | Questions and discussion |
| 10:40-11:00 | Break with refreshments |
| 11:00-11:30 | The Trønderbrain project – Next-generation translational medicine. Talk by Prof. Katja Scheffler, Laboratory leader at Department of Neurology, St. Olavs Hospital, Trondheim |
| 11:30-11:40 | Questions and discussion |
| 11:40-12:10 | The AD time project, Tora Bonnevie |
| 12:10-12:20 | Questions and discussion |
| 12:20-12:30 | Closing remarks |
| 12:30-12:45 | Organize for departure |
| 12:45-14:00 | Lunch |
| 14:00 | Departure |